# Api keys generated by Binance

class Api:
  api_key = 'weoQDOogSE7EUgxGps5yfz3HnHUQofjftWjFrIikC1JSJOuKnvgt3HYNvxAEKHNx'
  api_secret = '8biBDAfrDUxe2l0p4agscBvbBdQloXqQCWUP4XK3QUbQuZdPWgKfBc6WIsGRwsv2'