# Api keys generated by Binance

class Api:
  # api_key = 'weoQDOogSE7EUgxGps5yfz3HnHUQofjftWjFrIikC1JSJOuKnvgt3HYNvxAEKHNx'
  # api_secret = '8biBDAfrDUxe2l0p4agscBvbBdQloXqQCWUP4XK3QUbQuZdPWgKfBc6WIsGRwsv2'
  api_key = 'nH4SHVSgZOhRTLoUXlAKDjHxKVJpPOQwRCHaYnr9z6wmEqhhoMnqhRX9qVPKhPnI' #ivanex
  api_secret = '45d0hRIdgvnDG6mObkvcDu0lPn8epUcARVKZQo6FcwxRFzqqj8Fj9xS8AZT0IT27' #ivanex